GET http://localhost:8000/test

# Отделение одного запроса от другого
###

GET http://localhost:8000/test/lox

###

POST http://localhost:8000/test/lox
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345"
}

###

GET http://localhost:8000/todos/

###

POST http://localhost:8000/todos/
Content-Type: application/json

{
  "title": "Глебчик"
}